version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore(ci)'
    labels:
      - dependencies
    groups:
      github-actions-updates:
        patterns: ['*']
    cooldown:
      default-days: 7

  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7
    versioning-strategy: increase
    commit-message:
      prefix: 'fix'
      include: 'scope'
    labels:
      - dependencies
    groups:
      composer-dev-minor-patch:
        dependency-type: 'development'
        update-types: [minor, patch]
      # We don't bundle minor or major production assets, so they're tested individually.
      composer-patch:
        dependency-type: 'production'
        update-types: [patch]

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7
    versioning-strategy: increase
    commit-message:
      prefix: 'fix'
      include: 'scope'
    labels:
      - dependencies
    groups:
      npm-dev-minor-patch:
        dependency-type: 'development'
        update-types: [minor, patch]
      npm-prod-minor-patch:
        dependency-type: 'production'
        update-types: [minor, patch]

    # WordPress packages are bundled with WordPress core, and bumped manually when the minimum supported version changes.
    # `@wordpress/admin-ui` and `@wordpress/ui` are not bundled and can be updated independently.
    # New WordPress packages should be added to the ignore list here.
    ignore:
      - dependency-name: '@wordpress/a11y'
      - dependency-name: '@wordpress/abilities'
      - dependency-name: '@wordpress/api-fetch'
      - dependency-name: '@wordpress/block-editor'
      - dependency-name: '@wordpress/blocks'
      - dependency-name: '@wordpress/components'
      - dependency-name: '@wordpress/compose'
      - dependency-name: '@wordpress/core-abilities'
      - dependency-name: '@wordpress/core-data'
      - dependency-name: '@wordpress/data'
      - dependency-name: '@wordpress/dataviews'
      - dependency-name: '@wordpress/date'
      - dependency-name: '@wordpress/dom'
      - dependency-name: '@wordpress/dom-ready'
      - dependency-name: '@wordpress/edit-post'
      - dependency-name: '@wordpress/editor'
      - dependency-name: '@wordpress/element'
      - dependency-name: '@wordpress/hooks'
      - dependency-name: '@wordpress/i18n'
      - dependency-name: '@wordpress/icons'
      - dependency-name: '@wordpress/notices'
      - dependency-name: '@wordpress/plugins'
      - dependency-name: '@wordpress/primitives'
      - dependency-name: '@wordpress/url'
      - dependency-name: '@wordpress/wordcount'
